// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEGQu4RH1w7a40kkwNMjR21j-Ysxq_ngA',
    appId: '1:373914593004:web:da51d84d314f8a2158a7c9',
    messagingSenderId: '373914593004',
    projectId: 'sign-up-test-1',
    authDomain: 'sign-up-test-1.firebaseapp.com',
    databaseURL: 'https://sign-up-test-1-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-test-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HkwweTIr-EZrpVHjoz7d_3Sd29hfvy4',
    appId: '1:373914593004:android:e15e9041670398d658a7c9',
    messagingSenderId: '373914593004',
    projectId: 'sign-up-test-1',
    databaseURL: 'https://sign-up-test-1-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-test-1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChH4g8FPpU6D0dBWJsaxKHdrCW6PD1XD8',
    appId: '1:373914593004:ios:2e7626edf8ed496e58a7c9',
    messagingSenderId: '373914593004',
    projectId: 'sign-up-test-1',
    databaseURL: 'https://sign-up-test-1-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-test-1.appspot.com',
    androidClientId: '373914593004-riscn2tcu5vo9fc3c595jg6im4t49s5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChH4g8FPpU6D0dBWJsaxKHdrCW6PD1XD8',
    appId: '1:373914593004:ios:2e7626edf8ed496e58a7c9',
    messagingSenderId: '373914593004',
    projectId: 'sign-up-test-1',
    databaseURL: 'https://sign-up-test-1-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-test-1.appspot.com',
    androidClientId: '373914593004-riscn2tcu5vo9fc3c595jg6im4t49s5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEGQu4RH1w7a40kkwNMjR21j-Ysxq_ngA',
    appId: '1:373914593004:web:9ce0b956167e3d3a58a7c9',
    messagingSenderId: '373914593004',
    projectId: 'sign-up-test-1',
    authDomain: 'sign-up-test-1.firebaseapp.com',
    databaseURL: 'https://sign-up-test-1-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-test-1.appspot.com',
  );

}